# Mailboxes Pipeline

variables:
- group: MailboxNugetVariables

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.0.x'
  inputs:
    packageType: sdk
    version: 3.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: CmdLine@2
  displayName: 'Run Cake Script - Default'
  inputs:
    script: 'powershell -ExecutionPolicy ByPass -File build.ps1 -script "build.cake" -target "Default" -verbosity normal'

- task: CmdLine@2
  displayName: 'Run Cake Script - Publish (for master only)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    script: 'powershell -ExecutionPolicy ByPass -File build.ps1 -script "build.cake" -target "Publish" -verbosity normal'
  env:
    NugetPushKey: $(NugetPushKey)
    NugetPushSource: $(NugetPushSource)