# Mailboxes Pipeline

variables:
- group: MailboxNugetVariables

trigger:
- main
- develop

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1.x Runtime'
  inputs:
    packageType: runtime
    version: 3.1.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: UseDotNet@2
  displayName: 'Use .NET Core 5.0.x SDK'
  inputs:
    packageType: sdk
    version: 5.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: CmdLine@2
  displayName: 'Run Cake Script - Default'
  inputs:
    script: 'powershell -ExecutionPolicy ByPass -File build.ps1 -script "build.cake" -target "Default" -verbosity normal'

- task: CmdLine@2
  displayName: 'Run Cake Script - Publish (for main only)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    script: 'powershell -ExecutionPolicy ByPass -File build.ps1 -script "build.cake" -target "Publish" -verbosity normal'
  env:
    NugetPushKey: $(NugetPushKey)
    NugetPushSource: $(NugetPushSource)